containerize front-end app

diff --git a/services/msg-sender-backend/Makefile b/services/msg-sender-backend/Makefile
--- a/services/msg-sender-backend/Makefile
+++ b/services/msg-sender-backend/Makefile
@@ -1,38 +1,50 @@
 # HELP
 # This will output the help for each task
 # thanks to https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
-.PHONY: help clean package run-local test-local docker-build run-docker stop-docker test-docker check-updates generate-openapi
+.PHONY: help clean package run-local test-local docker-build docker-run docker-stop docker-clean docker-test check-updates generate-openapi
 
 .DEFAULT_GOAL := help
 
 help: ## This help
 	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
 
+DOCKER_REGISTRY=boeboe
+DOCKER_IMAGE=message-backend
+VERSION=1.0.0
+CONTAINER_PORT=80
+
 clean: ## Clean the project by removing target folder
+	@echo "Cleaning the project..."
 	mvn clean
 
 package: ## Package the project into a JAR file
+	@echo "Packaging the project into a JAR file..."
 	mvn clean package -U
 
 run-local: ## Run the Spring Boot application locally from JAR
+	@echo "Running Spring Boot application locally..."
 	mvn spring-boot:run
 
 test-local: ## Run integration tests against local Spring Boot app
+	@echo "Running integration tests against local Spring Boot app..."
 	mvn test -Dapi.base.url=http://localhost -Dapi.port=8080
 
 docker-build: ## Build multi-platform Docker image
+	@echo "Building Docker image..."
 	mvn clean package -DskipTests
-	docker buildx build --platform linux/amd64,linux/arm64 --push -t boeboe/message-service:latest .
+	docker buildx build --platform linux/amd64,linux/arm64 --push -t $(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION) .
 
-run-docker: docker-build ## Run the Docker image locally on port 8080
+docker-run: docker-build ## Run the Docker image locally on port 8080
+	@echo "Running Docker container 'message-service'..."
 	@if [ "$(shell docker ps -q -f name=message-service)" ]; then \
 		echo "Docker container 'message-service' is already running."; \
 	else \
 		echo "Starting Docker container 'message-service'..."; \
-		docker run -d --name message-service -p 8080:8080 boeboe/message-service:latest; \
+		docker run -d --name message-service -p 8080:$(CONTAINER_PORT) $(DOCKER_REGISTRY)/$(DOCKER_IMAGE):latest; \
 	fi
 
-stop-docker: ## Stop and remove the running Docker container
+docker-stop: ## Stop and remove the running Docker container
+	@echo "Stopping Docker container 'message-service'..."
 	@if [ "$(shell docker ps -q -f name=message-service)" ]; then \
 		echo "Stopping and removing Docker container 'message-service'..."; \
 		docker stop message-service && docker rm message-service; \
@@ -45,11 +57,21 @@ stop-docker: ## Stop and remove the running Docker container
 		fi \
 	fi
 
-test-docker: run-docker ## Run integration tests against the running Dockerized app
+docker-clean: ## Clean up old Docker images
+	@echo "Cleaning up old Docker images..."
+	@if [ "$(shell docker ps -a -q -f ancestor=$(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION))" ]; then \
+		echo "Forcing removal of the container..."; \
+		docker rm -f $(shell docker ps -a -q -f ancestor=$(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION)); \
+	fi
+	docker rmi -f $(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION) || true
+
+docker-test: docker-run ## Run integration tests against the running Dockerized app
+	@echo "Running integration tests against Dockerized app..."
 	./test.sh
-	$(MAKE) stop-docker
+	$(MAKE) docker-stop
 
 check-updates: ## Check for maven dependency updates
+	@echo "Checking for maven dependency updates..."
 	mvn versions:display-dependency-updates
 	mvn versions:display-plugin-updates
 
diff --git a/services/msg-sender-frontend/Makefile b/services/msg-sender-frontend/Makefile
--- a/services/msg-sender-frontend/Makefile
+++ b/services/msg-sender-frontend/Makefile
@@ -1,12 +1,17 @@
 # HELP
 # This will output the help for each task
 # thanks to https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
-.PHONY: help install build serve test clean
+.PHONY: help install build serve test clean docker-build docker-run docker-stop docker-clean
 
 .DEFAULT_GOAL := help
 
 help: ## This help
 	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z0-9_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
+
+DOCKER_REGISTRY=boeboe
+DOCKER_IMAGE=message-frontend
+VERSION=1.0.0
+CONTAINER_PORT=80
 
 install: ## Install node modules
 	@echo "Installing dependencies..."
@@ -27,3 +32,43 @@ test: ## Run tests
 clean: ## Clean the project
 	@echo "Cleaning the project..."
 	rm -rf dist
+
+docker-build: ## Build the Docker image
+	@echo "Building the Docker image..."
+	docker buildx build --platform linux/amd64,linux/arm64 --push -t $(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION) .
+
+docker-run: ## Run the Docker container
+	@echo "Running Docker container '$(DOCKER_IMAGE)'..."
+	@if [ "$(shell docker ps -q -f name=$(DOCKER_IMAGE))" ]; then \
+		echo "Docker container '$(DOCKER_IMAGE)' is already running."; \
+	else \
+		if [ "$(shell docker ps -a -q -f name=$(DOCKER_IMAGE))" ]; then \
+			echo "Starting existing container '$(DOCKER_IMAGE)'..."; \
+			docker start $(DOCKER_IMAGE); \
+		else \
+			echo "Starting new Docker container '$(DOCKER_IMAGE)'..."; \
+			docker run -d -p 8080:$(CONTAINER_PORT) --name $(DOCKER_IMAGE) -e BACKEND_URL=http://message-service $(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION); \
+		fi \
+	fi
+
+docker-stop: ## Stop and remove the Docker container
+	@echo "Stopping Docker container '$(DOCKER_IMAGE)'..."
+	@if [ "$(shell docker ps -q -f name=$(DOCKER_IMAGE))" ]; then \
+		echo "Stopping and removing running container '$(DOCKER_IMAGE)'..."; \
+		docker stop $(DOCKER_IMAGE) && docker rm $(DOCKER_IMAGE); \
+	else \
+		if [ "$(shell docker ps -a -q -f name=$(DOCKER_IMAGE))" ]; then \
+			echo "Removing stopped container '$(DOCKER_IMAGE)'..."; \
+			docker rm $(DOCKER_IMAGE); \
+		else \
+			echo "Docker container '$(DOCKER_IMAGE)' is not running."; \
+		fi \
+	fi
+
+docker-clean: ## Clean up old Docker images
+	@echo "Cleaning up old Docker images..."
+	@if [ "$(shell docker ps -a -q -f ancestor=$(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION))" ]; then \
+		echo "Forcing removal of the container..."; \
+		docker rm -f $(shell docker ps -a -q -f ancestor=$(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION)); \
+	fi
+	docker rmi -f $(DOCKER_REGISTRY)/$(DOCKER_IMAGE):$(VERSION) || true
